project-includes = ["app/**/*.py"]
project-excludes = [".venv/**", "venv/**", "**/__pycache__/**"]

search-path = [".", ".venv/Lib/site-packages"]

python-interpreter-path = ".venv/Scripts/python.exe"